[package]
    edition = "2024"
    name    = "pyopath"
    version = "0.1.0"

[lib]
    crate-type = ["cdylib"]
    name       = "pyopath"

[dependencies]
    dirs = "6"
    pyo3 = { version = "0.27", features = ["extension-module"] }
